### PR TITLE
New icons to upload

### PR DESCRIPTION
**Pull request by funkmeister7**

### CODE REVIEW

**Comment by funkmeister7** [comment]
Please consider for uploading new icon resources

**Comment by ronie** [comment]
there seem to be a few Record Labels (A&M, Epic, Island, etc...) included in this PR.
i don't think that is needed?

**Comment by funkmeister7** [comment]
Yes @ronie, you're correct.  There are a few record labels, which are for music DVDs which is why they are in the "move" collection.  Is it correct these labels should be in this collection for music DVDs?

**Comment by ronie** [comment]
nope, we have another addon for record labels:
https://github.com/XBMC-Addons/resource.images.recordlabels.white

skins can use that one to show logos for music dvd's

**Comment by funkmeister7** [comment]
Ahh, I see.  I'll adjust the content for this one and let you know.

**Comment by funkmeister7** [comment]
Hi @ronie.  I have removed the music labels from this collection

**Comment by ronie** [comment]
great, thx!

**Pull request merged**
