### PR TITLE
Created a few new images

### PR DESCRIPTION
**Pull request by AMoo-Miki**
Updated Lifetime's logo and created a few new ones

### CODE REVIEW

**Comment by AMoo-Miki** [comment]
@ronie, would you be open to enabling "issues" for this repo? I would drop in once in a while to fill in people's requests.

**Comment by ronie** [comment]
sure, no problem.
issues is now enabled.

**Comment by AMoo-Miki** [comment]
awesome. thanks :)

**Comment by ronie** [comment]
will invite you as a collaborator.
makes it easier for you to keep track of things.. and feel free to merge your own PR's ;-)

**Comment by AMoo-Miki** [comment]
Thanks a ton.

**Comment by thezoggy** [comment]
> Lifetime.png

while is valid, there should also be a `Lifetime (US).png`
~[tvdb](http://zoggy.net/firefox_2018-09-17_18-10-19.png)

additionally, it could use an update to be more readable:

lifetime

**Comment by AMoo-Miki** [comment]
I'll add Lifetime (US).

Regarding the logo, I tried to find how they themselves use their logo in white on a dark background and I found [this](http://www.justjared.com/photo-gallery/4076547/murray-fraser-parisa-fitz-henley-step-out-for-lifetime-harry-meghan-premiere-04/) from last May. After reading your comment, I found [this](https://s.newsweek.com/sites/www.newsweek.com/files/styles/full/public/2018/09/10/gettyimages-1028019074.jpg) from last week. I will update the logo to match the newer one.

Thanks for that.

**Comment by thezoggy** [comment]
ty very much!

**Pull request merged**
