### PR TITLE
Add new studios icons

### PR DESCRIPTION
**Pull request by gade01**
3 new studio icons:

- SVT 1
- TV 2 (DK)
- TV3 (NO)

Thanks to @nwalma

### CODE REVIEW

**Comment by ronie** [comment]
looks good to me, thx!

**Comment by Nwalma** [comment]
thank you both

@ronie do you know when the next update for this addon will be available?

**Comment by gade01** [comment]
@Nwalma I can bump the addon version on the next PR.

**Comment by Nwalma** [comment]
👍

**Pull request merged**
