### PR TITLE
New imagery

### PR DESCRIPTION
**Pull request by AMoo-Miki**
I added some new images, and upgraded Playtone.

### CODE REVIEW

**Comment by ronie** [comment]
thx again!

**Comment by AMoo-Miki** [comment]
:) my pleasure.

**Comment by AMoo-Miki** [comment]
@ronie, I was thinking of files that are in all lowercase like "lucasfilm". While the will show up fine on Windows, case-sensitive operating systems will have a problem with them. Would you like me to make the changes?

**Comment by ronie** [comment]
yes, please.. that'd be great!
you're correct, filenames need proper casing in order to work on all OS's.

**Pull request merged**
